Working parcer, plain text db output

diff --git a/parcer b/parcer
--- a/parcer
+++ b/parcer
@@ -8,6 +8,11 @@ else
 	mkdir /tmp/rutr_saver_tmp
 	cd /tmp/rutr_saver_tmp
 fi
+if ! [ -d /var/log/rutr_saver_log]; then
+	sudo mkdir /var/log/rutr_saver_log
+	sleep 30
+fi
+
 
 start_time=$(date)
 
@@ -26,7 +31,6 @@ fi
 
 forum_count=$(cat index_scrape | wc -l)
 i=o
-cat index_scrape > index_scrape_t0
 
 until ((i == $forum_count));do
 	forum_id=$(cat index_scrape | awk NR==$i)
@@ -45,13 +49,12 @@ done
 
 # kostyl` to hotfix previous bug
 
-cat index_scrape > index_scrape_t1
 cat index_scrape | sort -n | uniq > final_scrape && rm index_scrape
 
 # cleaning temp files & logging
 
 rm forum_scrape forum.html index_scrape_sort uniq_scrape
-echo "[DEBUG][SCRAPER] Forum scraping; Start: $start_time; End: $(date); Forums scraped $(cat final_scrape | wc -l); " >> rutrsaver.log
+echo "[DEBUG][SCRAPER] Forum scraping; Start: $start_time; End: $(date); Forums scraped $(cat final_scrape | wc -l); " >>/var/log/rutr_saver_log/rutrsaver.log
 
 # scraping pages for topic lists
 
@@ -89,5 +92,67 @@ until ((i == $forum_count));do
 done
 
 cat page_scrape | sort -n | uniq > topic_scrape && rm page_scrape 
-echo "[DEBUG][SCRAPER] Topic scraping; Start: $start_time; End: $(date); Topics scraped: $(cat topic_scrape | wc -l);" >> rutrsaver.log
+echo "[DEBUG][SCRAPER] Topic scraping; Start: $start_time; End: $(date); Topics scraped: $(cat topic_scrape | wc -l);" >> /var/log/rutr_saver_log/rutrsaver.log
 
+# scraping topics and saving final file
+
+start_time=$(date)
+topic_count=$(cat topic_scrape | wc -l)
+i=0
+
+until ((i == $topic_count));do
+        topic_id=$(cat topic_scrape | awk NR==$i)
+        clear
+        echo "Scraping topic $i from $topic_count"
+        wget --output-document="topic.html" --load-cookies=/home/vdpd/wgetcookies.txt "https://rutracker.org/forum/viewtopic.php?t=$topic_id"
+        if [ -s topic.html ]; then
+                t_seeds=$(iconv -f cp1251 topic.html | grep "Сиды" | cut -d ">" -f 3 | sed -r 's/[^[0-9]*$//')
+                t_size=$(iconv -f cp1251 topic.html | grep "Размер" | awk NR==1 | cut -d ">" -f 2  | sed -r 's/[^[0-9]*$//')
+                t_degree=$(iconv -f cp1251 topic.html | grep "Размер" | awk NR==1 | cut -d ">" -f 2  | cut -d ";" -f 2 | sed -r 's/[^[B]*$//')
+                t_magnet=$(iconv -f cp1251 topic.html | grep magnet: | sed -r 's/^[^"]*//'| cut -d" " -f1)
+                if [ "$t_seeds" ] && [ "$t_size" ] && [ "$t_degree" ] && [ "$t_magnet" ]; then
+                        if (($t_seeds == 1)) && (($(echo "$t_size > 2" | bc) ==1)) && (($(echo "$t_size < 50" | bc) ==1)) && [ $t_degree == "GB" ] ; then
+                                 echo "${topic_id};${t_magnet};${t_size};" >> NH_topics
+                                 clear
+                                 echo "Nice one!"
+				 t_nice=$(($t_nice + 1))
+                                 sleep 0.5
+                        elif (($t_seeds != 1)); then
+                                clear
+                                echo "Seeds number is too low or too high"
+                                sleep 0.5
+				t_bad=$(($t_bad + 1))
+                        elif (($(echo "$t_size < 2" | bc) ==1)) || [ $t_degree != "GB" ]; then
+                                clear
+                                echo "Size is too small"
+                                sleep 0.5
+				t_bad=$(($t_bad + 1))
+                        elif (($(echo "$t_size > 50" | bc) ==1)); then
+                                clear
+                                echo "Size is too big"
+                                sleep 0.5
+				t_bad=$(($t_bad + 1))
+                        else
+                                clear
+                                echo "BAD conditions"
+                                echo "[ERROR][CONDITIONS]${topic_id};${t_magnet};${t_size}${t_degree};${t_seeds};" >> BAD_topics
+                                sleep 0.5
+				t_bad=$(($t_bad + 1))
+                        fi
+                else
+                        clear
+                        echo "BAD topic"
+                        sleep 0.5
+			t_bad=$(($t_bad + 1))
+                fi
+                rm topic.html
+                t_seeds=$devnull
+                t_size=$devnull
+                t_degree=$devnull
+                t_magnet=$devnull
+        fi
+        ((++i))
+done
+
+rm topic_scrape
+echo "[DEBUG][SCRAPER] Torrent scraping; Start: $start_time; End: $(date); Torrent scraped: $t_nice; Useless torrents: $t_bad" >> /var/log/rutr_saver_log/rutrsaver.log
